version: "3"
services:
  postgres:
    container_name: nest-typeorm-db-db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: nest-typeorm-db-admin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  postgres:
    driver: bridge